# Generated by Django 3.0.4 on 2020-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='series',
            name='ratings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
